### ISSUE TITLE
Duplicate transaction on Transact()

### ISSUE THREAD

**Issue by susruth** [republicprotocol/beth-go#3]
**Description**

The Transact(...) function call sometimes creates duplicate transactions. This is a critical issue, as one of the main reasons for this library to exist is idempotent transactions.  

**Expected Behavior**

```go 
Transact(ctx context.Context, preConditionCheck func() bool, f func(*bind.TransactOpts) (*types.Transaction, error), postConditionCheck func() bool, waitForBlocks int64) error
```
should only ever create a single transaction, but is trying to create multiple transactions, fails (as the contract does not allow it) and gets trapped in an infinite loop.

**Steps to reproduce**

It is non-deterministic but can be replicated by trying to do multiple write functions with postconditions.

**Version**

Current Version

**Operating system**

Any

**Comment by tok-kkk** [comment]
Close this issue as it has been fixed in PR #6.
