### ISSUE TITLE
WaitMined() returns an empty receipt

### ISSUE THREAD

**Issue by jazg** [republicprotocol/beth-go#4]
**Description**

The `WaitMined(...)` function call seems to return empty receipts. This is an issue when calling `Transact(...)`, as this function is not able to pass the `TxBlockNumber(...)` stage because of the empty `txHash` being passed into it. This then hangs until the context deadline is exceeded. It is worth noting the transaction does in fact go through.

I added some logs inside the `Transact(...)` function that confirm the issue.

```go
log.Println("before TxBlockNumber()")
blockNumber, err := account.client.TxBlockNumber(ctx, txHash.String())
if err != nil {
	log.Println("TxBlockNumber() error")
	return err
}
log.Println("after TxBlockNumber()")
```

The third log never gets printed. I added further logs inside the `TxBlockNumber(...)` which get printed continuously until the context deadline is exceeded. This is because the `txHash.String()` value is zero and hence the Infura response is invalid, so we get stuck retrying inside the loop.

**Expected behaviour**

```go
WaitMined(ctx context.Context, tx *types.Transaction) (*types.Receipt, error)
```
should never return an empty receipt.

**Steps to reproduce**

Occurs whenever I call the `Transact(...)` function.

**Version**

Current version (commit hash `cc6dabd`)

**Operating system**

Any

**Comment by tok-kkk** [comment]
Close this as it has been fixed in #7
