### ISSUE TITLE
Panics sometimes on Transact(...)

### ISSUE THREAD

**Issue by susruth** [republicprotocol/beth-go#5]
**Description**

The Transact(...) function call sometimes crashes. This is a critical issue, as we expect beth-go to be fault tolerant.

**Expected Behavior**

```go 
Transact(ctx context.Context, preConditionCheck func() bool, f func(*bind.TransactOpts) (*types.Transaction, error), postConditionCheck func() bool, waitForBlocks int64) error
```
should not panic because of runtime errors.

**Steps to reproduce**

This happens when beth-go cannot receive the gas price from eth gas station.
```go
GasPrice: big.NewInt(0).Set(account.transactOpts.GasPrice)
```
`account.transactOpts.GasPrice` is nil by default

**Version**

Current Version

**Operating system**

Any

**Comment by tok-kkk** [comment]
Close this as it has been fixed in #7
